onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mips_vhd_tst/clk
add wave -noupdate /mips_vhd_tst/rst
add wave -noupdate /mips_vhd_tst/i1/outs
add wave -noupdate /mips_vhd_tst/i1/clk
add wave -noupdate /mips_vhd_tst/i1/rst
add wave -noupdate /mips_vhd_tst/i1/sig_OUT_PCP4_2
add wave -noupdate /mips_vhd_tst/i1/sig_OUT_jump
add wave -noupdate /mips_vhd_tst/i1/sig_OUT_memI_1
add wave -noupdate /mips_vhd_tst/i1/sig_inst
add wave -noupdate /mips_vhd_tst/i1/sig_regData
add wave -noupdate /mips_vhd_tst/i1/sig_dadoLido1
add wave -noupdate /mips_vhd_tst/i1/sig_dadoLido2
add wave -noupdate /mips_vhd_tst/i1/sig_imediate_ext
add wave -noupdate /mips_vhd_tst/i1/sig_dadoLido1_1
add wave -noupdate /mips_vhd_tst/i1/sig_dadoLido2_1
add wave -noupdate /mips_vhd_tst/i1/sig_imediate_ext_1
add wave -noupdate /mips_vhd_tst/i1/sig_somInPC
add wave -noupdate /mips_vhd_tst/i1/sig_IN1_ULA
add wave -noupdate /mips_vhd_tst/i1/sig_IN2_ULA
add wave -noupdate /mips_vhd_tst/i1/sig_ULA_result
add wave -noupdate /mips_vhd_tst/i1/sig_OUT_PCP4_3
add wave -noupdate /mips_vhd_tst/i1/sig_in_PC
add wave -noupdate /mips_vhd_tst/i1/sig_out_PC
add wave -noupdate /mips_vhd_tst/i1/sig_OUT_jump_1
add wave -noupdate /mips_vhd_tst/i1/sig_ULA_result_1
add wave -noupdate /mips_vhd_tst/i1/sig_dadoLido2_2
add wave -noupdate /mips_vhd_tst/i1/sig_OUT_memD
add wave -noupdate /mips_vhd_tst/i1/sig_OUT_memD_1
add wave -noupdate /mips_vhd_tst/i1/sig_ULA_result_2
add wave -noupdate /mips_vhd_tst/i1/sig_OUT_PCP4_1
add wave -noupdate /mips_vhd_tst/i1/in_PIPE1
add wave -noupdate /mips_vhd_tst/i1/out_PIPE1
add wave -noupdate /mips_vhd_tst/i1/sig_opcode
add wave -noupdate /mips_vhd_tst/i1/sig_function
add wave -noupdate /mips_vhd_tst/i1/sig_ReadReg1
add wave -noupdate /mips_vhd_tst/i1/sig_ReadReg2
add wave -noupdate /mips_vhd_tst/i1/sig_regDest
add wave -noupdate /mips_vhd_tst/i1/sig_RegEsc
add wave -noupdate /mips_vhd_tst/i1/sig_ReadReg2_1
add wave -noupdate /mips_vhd_tst/i1/sig_regDest_1
add wave -noupdate /mips_vhd_tst/i1/sig_RegEsc_1
add wave -noupdate /mips_vhd_tst/i1/sig_RegEsc_0
add wave -noupdate /mips_vhd_tst/i1/sig_RegEsc_2
add wave -noupdate /mips_vhd_tst/i1/sig_imediate
add wave -noupdate /mips_vhd_tst/i1/sig_adiantaB1
add wave -noupdate /mips_vhd_tst/i1/sig_adiantaA1
add wave -noupdate /mips_vhd_tst/i1/sig_adiantaA
add wave -noupdate /mips_vhd_tst/i1/sig_adiantaB
add wave -noupdate /mips_vhd_tst/i1/sig_ulaOp
add wave -noupdate /mips_vhd_tst/i1/sig_ulaOp_1
add wave -noupdate /mips_vhd_tst/i1/sig_ulaFonte
add wave -noupdate /mips_vhd_tst/i1/sig_ulaFonte_1
add wave -noupdate /mips_vhd_tst/i1/sig_escMem
add wave -noupdate /mips_vhd_tst/i1/sig_escMem_1
add wave -noupdate /mips_vhd_tst/i1/sig_lerMem
add wave -noupdate /mips_vhd_tst/i1/sig_lerMem_1
add wave -noupdate /mips_vhd_tst/i1/sig_DvC
add wave -noupdate /mips_vhd_tst/i1/sig_DvC_1
add wave -noupdate /mips_vhd_tst/i1/sig_memParaReg
add wave -noupdate /mips_vhd_tst/i1/sig_memParaReg_1
add wave -noupdate /mips_vhd_tst/i1/sig_fontePC
add wave -noupdate /mips_vhd_tst/i1/we3
add wave -noupdate /mips_vhd_tst/i1/sig_escReg_1
add wave -noupdate /mips_vhd_tst/i1/sig_ULA_zero
add wave -noupdate /mips_vhd_tst/i1/sig_RegDST
add wave -noupdate /mips_vhd_tst/i1/sig_escMem_2
add wave -noupdate /mips_vhd_tst/i1/sig_lerMem_2
add wave -noupdate /mips_vhd_tst/i1/sig_DvC_2
add wave -noupdate /mips_vhd_tst/i1/sig_memParaReg_2
add wave -noupdate /mips_vhd_tst/i1/sig_escReg_2
add wave -noupdate /mips_vhd_tst/i1/sig_ULA_zero_1
add wave -noupdate /mips_vhd_tst/i1/sig_memParaReg_3
add wave -noupdate /mips_vhd_tst/i1/sig_escReg_3
add wave -noupdate /mips_vhd_tst/i1/sig_escReg
add wave -noupdate /mips_vhd_tst/i1/sig_RegDST_1
add wave -noupdate /mips_vhd_tst/i1/sig_operULA
add wave -noupdate /mips_vhd_tst/i1/in_PIPE3
add wave -noupdate /mips_vhd_tst/i1/out_PIPE3
add wave -noupdate /mips_vhd_tst/i1/in_PIPE4
add wave -noupdate /mips_vhd_tst/i1/out_PIPE4
add wave -noupdate /mips_vhd_tst/i1/in_PIPE2
add wave -noupdate /mips_vhd_tst/i1/out_pipe2
add wave -noupdate /mips_vhd_tst/i1/in_PIPEAUX
add wave -noupdate /mips_vhd_tst/i1/out_pipeaux
add wave -noupdate /mips_vhd_tst/i1/PC1/clk
add wave -noupdate /mips_vhd_tst/i1/PC1/rst
add wave -noupdate /mips_vhd_tst/i1/PC1/D
add wave -noupdate /mips_vhd_tst/i1/PC1/Q
add wave -noupdate /mips_vhd_tst/i1/PC1/Temp
add wave -noupdate /mips_vhd_tst/i1/mux_IN_PC/SEL
add wave -noupdate /mips_vhd_tst/i1/mux_IN_PC/A
add wave -noupdate /mips_vhd_tst/i1/mux_IN_PC/B
add wave -noupdate /mips_vhd_tst/i1/mux_IN_PC/X
add wave -noupdate /mips_vhd_tst/i1/PCP4/a
add wave -noupdate /mips_vhd_tst/i1/PCP4/b
add wave -noupdate /mips_vhd_tst/i1/PCP4/add_sub
add wave -noupdate /mips_vhd_tst/i1/PCP4/result
add wave -noupdate /mips_vhd_tst/i1/memI/data
add wave -noupdate /mips_vhd_tst/i1/memI/address
add wave -noupdate /mips_vhd_tst/i1/memI/clock
add wave -noupdate /mips_vhd_tst/i1/memI/wren
add wave -noupdate /mips_vhd_tst/i1/memI/q
add wave -noupdate /mips_vhd_tst/i1/PIPE1/clk
add wave -noupdate /mips_vhd_tst/i1/PIPE1/rst
add wave -noupdate /mips_vhd_tst/i1/PIPE1/D
add wave -noupdate /mips_vhd_tst/i1/PIPE1/Q
add wave -noupdate /mips_vhd_tst/i1/PIPE1/Temp
add wave -noupdate /mips_vhd_tst/i1/controle/clk
add wave -noupdate /mips_vhd_tst/i1/controle/rst
add wave -noupdate /mips_vhd_tst/i1/controle/opcode
add wave -noupdate /mips_vhd_tst/i1/controle/ulaOp
add wave -noupdate /mips_vhd_tst/i1/controle/RegDst
add wave -noupdate /mips_vhd_tst/i1/controle/escMem
add wave -noupdate /mips_vhd_tst/i1/controle/lerMem
add wave -noupdate /mips_vhd_tst/i1/controle/DvC
add wave -noupdate /mips_vhd_tst/i1/controle/memParaReg
add wave -noupdate /mips_vhd_tst/i1/controle/escReg
add wave -noupdate /mips_vhd_tst/i1/controle/reg1
add wave -noupdate /mips_vhd_tst/i1/controle/reg2
add wave -noupdate /mips_vhd_tst/i1/controle/reg3
add wave -noupdate /mips_vhd_tst/i1/controle/adiantaA
add wave -noupdate /mips_vhd_tst/i1/controle/adiantaB
add wave -noupdate /mips_vhd_tst/i1/controle/combination0
add wave -noupdate /mips_vhd_tst/i1/controle/combination1
add wave -noupdate /mips_vhd_tst/i1/controle/sinal11
add wave -noupdate /mips_vhd_tst/i1/controle/sinal22
add wave -noupdate /mips_vhd_tst/i1/controle/sinal33
add wave -noupdate /mips_vhd_tst/i1/controle/sinal44
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/clk
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/rst
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/reg1
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/reg2
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/reg3
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/sinal1
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/sinal2
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/sinal3
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/sinal4
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/rs0
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/rs1
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip1/clk
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip1/rst
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip1/D
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip1/Q
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip1/Temp
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip2/clk
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip2/rst
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip2/D
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip2/Q
add wave -noupdate /mips_vhd_tst/i1/controle/igualitario/Flip2/Temp
add wave -noupdate /mips_vhd_tst/i1/controle/gerador/opcode
add wave -noupdate /mips_vhd_tst/i1/controle/gerador/sinal1
add wave -noupdate /mips_vhd_tst/i1/controle/gerador/sinal2
add wave -noupdate /mips_vhd_tst/i1/controle/gerador/sinal3
add wave -noupdate /mips_vhd_tst/i1/controle/gerador/sinal4
add wave -noupdate /mips_vhd_tst/i1/controle/gerador/AdiantaA
add wave -noupdate /mips_vhd_tst/i1/controle/gerador/AdiantaB
add wave -noupdate /mips_vhd_tst/i1/controle/gerador/AdiantaA1
add wave -noupdate /mips_vhd_tst/i1/controle/gerador/AdiantaB1
add wave -noupdate /mips_vhd_tst/i1/registradores/A1
add wave -noupdate /mips_vhd_tst/i1/registradores/A2
add wave -noupdate /mips_vhd_tst/i1/registradores/A3
add wave -noupdate /mips_vhd_tst/i1/registradores/clk
add wave -noupdate /mips_vhd_tst/i1/registradores/rst
add wave -noupdate /mips_vhd_tst/i1/registradores/we3
add wave -noupdate /mips_vhd_tst/i1/registradores/wd3
add wave -noupdate /mips_vhd_tst/i1/registradores/out1
add wave -noupdate /mips_vhd_tst/i1/registradores/out2
add wave -noupdate /mips_vhd_tst/i1/registradores/OregImux
add wave -noupdate /mips_vhd_tst/i1/registradores/Odec
add wave -noupdate /mips_vhd_tst/i1/registradores/Ien
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(0)/regb/en
add wave -noupdate -radix decimal /mips_vhd_tst/i1/registradores/G2(0)/regb/D
add wave -noupdate -radix unsigned /mips_vhd_tst/i1/registradores/G2(0)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(0)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(1)/regb/rst
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(1)/regb/en
add wave -noupdate -radix unsigned /mips_vhd_tst/i1/registradores/G2(1)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(1)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(1)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(2)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(2)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(2)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(2)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(3)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(3)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(3)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(3)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(4)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(4)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(4)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(4)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(5)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(5)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(5)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(5)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(6)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(6)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(6)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(6)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(7)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(7)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(7)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(7)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(8)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(8)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(8)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(8)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(9)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(9)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(9)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(9)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(10)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(10)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(10)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(10)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(11)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(11)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(11)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(11)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(12)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(12)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(12)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(12)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(13)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(13)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(13)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(13)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(14)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(14)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(14)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(14)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(15)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(15)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(15)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(15)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(16)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(16)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(16)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(16)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(17)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(17)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(17)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(17)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(18)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(18)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(18)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(18)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(19)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(19)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(19)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(19)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(20)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(20)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(20)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(20)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(21)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(21)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(21)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(21)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(22)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(22)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(22)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(22)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(23)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(23)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(23)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(23)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(24)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(24)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(24)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(24)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(25)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(25)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(25)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(25)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(26)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(26)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(26)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(26)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(27)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(27)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(27)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(27)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(28)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(28)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(28)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(28)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(29)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(29)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(29)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(29)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(30)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(30)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(30)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(30)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(31)/regb/en
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(31)/regb/D
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(31)/regb/Q
add wave -noupdate /mips_vhd_tst/i1/registradores/G2(31)/regb/Temp
add wave -noupdate /mips_vhd_tst/i1/registradores/outData1/input
add wave -noupdate /mips_vhd_tst/i1/registradores/outData1/sel
add wave -noupdate /mips_vhd_tst/i1/registradores/outData1/output
add wave -noupdate /mips_vhd_tst/i1/registradores/outData2/input
add wave -noupdate /mips_vhd_tst/i1/registradores/outData2/sel
add wave -noupdate /mips_vhd_tst/i1/registradores/outData2/output
add wave -noupdate /mips_vhd_tst/i1/registradores/decWrite/input
add wave -noupdate /mips_vhd_tst/i1/registradores/decWrite/output
add wave -noupdate /mips_vhd_tst/i1/ExtSinal/in16
add wave -noupdate /mips_vhd_tst/i1/ExtSinal/out32
add wave -noupdate /mips_vhd_tst/i1/PIPE2/clk
add wave -noupdate /mips_vhd_tst/i1/PIPE2/rst
add wave -noupdate /mips_vhd_tst/i1/PIPE2/D
add wave -noupdate /mips_vhd_tst/i1/PIPE2/Q
add wave -noupdate /mips_vhd_tst/i1/PIPE2/Temp
add wave -noupdate /mips_vhd_tst/i1/PIPEAUX/clk
add wave -noupdate /mips_vhd_tst/i1/PIPEAUX/rst
add wave -noupdate /mips_vhd_tst/i1/PIPEAUX/D
add wave -noupdate /mips_vhd_tst/i1/PIPEAUX/Q
add wave -noupdate /mips_vhd_tst/i1/PIPEAUX/Temp
add wave -noupdate /mips_vhd_tst/i1/inPC/a
add wave -noupdate /mips_vhd_tst/i1/inPC/b
add wave -noupdate /mips_vhd_tst/i1/inPC/add_sub
add wave -noupdate /mips_vhd_tst/i1/inPC/result
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_1/SEL
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_1/A
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_1/B
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_1/C
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_1/D
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_1/X
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_2/SEL
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_2/A
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_2/B
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_2/C
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_2/D
add wave -noupdate /mips_vhd_tst/i1/mux_IN_ULA_4_2/X
add wave -noupdate /mips_vhd_tst/i1/operaULA/ULAop
add wave -noupdate /mips_vhd_tst/i1/operaULA/funct
add wave -noupdate /mips_vhd_tst/i1/operaULA/oper
add wave -noupdate /mips_vhd_tst/i1/ULA1/in0
add wave -noupdate /mips_vhd_tst/i1/ULA1/in1
add wave -noupdate /mips_vhd_tst/i1/ULA1/oper
add wave -noupdate /mips_vhd_tst/i1/ULA1/zero
add wave -noupdate /mips_vhd_tst/i1/ULA1/output
add wave -noupdate /mips_vhd_tst/i1/ULA1/sig_output
add wave -noupdate /mips_vhd_tst/i1/muxEscReg/SEL
add wave -noupdate /mips_vhd_tst/i1/muxEscReg/A
add wave -noupdate /mips_vhd_tst/i1/muxEscReg/B
add wave -noupdate /mips_vhd_tst/i1/muxEscReg/X
add wave -noupdate /mips_vhd_tst/i1/PIPE3/clk
add wave -noupdate /mips_vhd_tst/i1/PIPE3/rst
add wave -noupdate /mips_vhd_tst/i1/PIPE3/D
add wave -noupdate /mips_vhd_tst/i1/PIPE3/Q
add wave -noupdate /mips_vhd_tst/i1/PIPE3/Temp
add wave -noupdate /mips_vhd_tst/i1/memD/address
add wave -noupdate /mips_vhd_tst/i1/memD/clock
add wave -noupdate /mips_vhd_tst/i1/memD/data
add wave -noupdate /mips_vhd_tst/i1/memD/wren
add wave -noupdate /mips_vhd_tst/i1/memD/q
add wave -noupdate /mips_vhd_tst/i1/memD/sub_wire0
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/wren_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/wren_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/rden_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/rden_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/data_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/data_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/address_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/address_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/clock0
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/clock1
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/clocken0
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/clocken1
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/clocken2
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/clocken3
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/aclr0
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/aclr1
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/addressstall_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/addressstall_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/byteena_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/byteena_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/q_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/q_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/eccstatus
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_data_reg_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_data_reg_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_reg_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_tmp_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_tmp2_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_tmp_wren_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_tmp2_wren_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_tmp_wren_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_reg_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_tmp_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_tmp2_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_output_latch
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_ecc_reg_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_q_ecc_tmp_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_current_written_data_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_original_data_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_original_data_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_mask_reg_a_x
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_mask_reg_b_x
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_mask_reg_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_mask_reg_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_mask_reg_a_out
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_mask_reg_b_out
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_mask_reg_a_out_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_mask_reg_b_out_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_address_reg_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_address_reg_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_wren_reg_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_wren_reg_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_rden_reg_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_rden_reg_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_read_flag_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_read_flag_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_reread_flag_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_reread_flag_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_reread_flag2_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_reread_flag2_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_write_flag_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_write_flag_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_nmram_write_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_nmram_write_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_indata_aclr_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_address_aclr_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_wrcontrol_aclr_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_indata_aclr_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_address_aclr_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_wrcontrol_aclr_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_outdata_aclr_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_outdata_aclr_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_rdcontrol_aclr_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_aclr_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_byteena_aclr_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/good_to_go_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/good_to_go_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_core_clocken_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_core_clocken_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_core_clocken_b0
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_core_clocken_b1
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_inclocken0
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_input_clocken_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_outdata_clken_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_outdata_clken_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_outlatch_clken_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_outlatch_clken_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_core_clocken_a_reg
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_core_clocken_b_reg
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/default_val
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_data_zero_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_data_zero_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_data_ones_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_data_ones_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/same_clock_pulse0
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/same_clock_pulse1
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_force_reread_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_force_reread_a1
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_force_reread_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_force_reread_b1
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_force_reread_signal_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_force_reread_signal_b
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_good_to_write_a
add wave -noupdate /mips_vhd_tst/i1/memD/altsyncram_component/i_good_to_write_b
add wave -noupdate /mips_vhd_tst/i1/PIPE4/clk
add wave -noupdate /mips_vhd_tst/i1/PIPE4/rst
add wave -noupdate /mips_vhd_tst/i1/PIPE4/D
add wave -noupdate /mips_vhd_tst/i1/PIPE4/Q
add wave -noupdate /mips_vhd_tst/i1/PIPE4/Temp
add wave -noupdate /mips_vhd_tst/i1/muxEscReg2/SEL
add wave -noupdate /mips_vhd_tst/i1/muxEscReg2/A
add wave -noupdate /mips_vhd_tst/i1/muxEscReg2/B
add wave -noupdate /mips_vhd_tst/i1/muxEscReg2/X
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {50000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 440
configure wave -valuecolwidth 391
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {138810 ps}
